### ISSUE TITLE
Schrats display 2 Uproot skills in their combat tooltip

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/mod-reforged#281]
![image](https://github.com/Battle-Modders/mod-reforged/assets/2252464/38856906-7a6f-4d1d-a758-b4cd233036fd)

![image](https://github.com/Battle-Modders/mod-reforged/assets/2252464/a862471c-1a07-4d7d-a66a-e2643b376b64)

Maybe the solution here is to introduce a new boolean for skills which decides whether they are shown/hidden in the combat tooltip.

**Comment by Darxo** [comment]
The same is true for Unholds:
![image](https://github.com/Battle-Modders/mod-reforged/assets/2252464/560024c8-7c8b-42ef-8df2-c517e02d5cc0)

**Comment by LordMidas** [comment]
Should be resolved as of #452
