### ISSUE TITLE
No concept for Vision

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/mod-reforged#349]
Currently no concept/nested tooltip for the mechanic of **Vision** exists

Here some bullet points:
- Vision controls how far this character can see on the battlefield
- The range of most skills is limited by the vision of the character
- Vision is lower at night
- Vision is reduced by certain helmets

**Comment by Darxo** [comment]
I don't see where we implemented such a concept/nested tooltip.

**Comment by LordMidas** [comment]
> I don't see where we implemented such a concept/nested tooltip.

https://github.com/Battle-Modders/mod-reforged/commit/09ebb9253dfb1ea35fba660c0f3c3ad615c91f46
