### ISSUE TITLE
[Style] Remove comma from every last element in perk_defs.nut

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/mod-reforged#375]
Unlike in vanilla perks.nut, we added a comma after the last entry in the reforged perks_defs.nut table like so:

![image](https://github.com/Battle-Modders/mod-reforged/assets/2252464/65bb1a7c-44d3-467a-a6f6-fca9e13c1ee1)

This should be fixed during a clean-up commit

**Comment by LordMidas** [comment]
Done in d166b85cc28ca573686122a874b515de0de0ca2b
