### ISSUE TITLE
Fullstop is sometimes moved to new line when using nested tooltips

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/mod-reforged#378]
![330215786-24ca5090-a2f1-4b10-a8c7-e0bb5e1fcbf2](https://github.com/Battle-Modders/mod-reforged/assets/2252464/97acf12f-e3de-4a5a-8d78-9224f51d5240)

This tooltip is the result of the following code
```
this.m.Description = ::Reforged.Mod.Tooltips.parseString("Encourage an ally to raise their current [Morale|Concept.Morale]. A character can only be encouraged once per round. Cannot be used on fleeing or [stunned|Skill+stunned_effect] allies.");
```

Usually those fullstops are considered part of the word and cause the full word to move into the next line. But the nested tooltip tech seems to break this rule.

**Comment by LordMidas** [comment]
I don't know if there is a reasonable fix for this except that we start putting fullstops within the nested tooltip hyperlink text. However, in this case that'd mean that the entire `Morale.` moves to the next line leaving a large gap up there on the first line which also doesn't look good. Pulling @Enduriel and @TaroEld into the conversation.

**Comment by Enduriel** [comment]
I would just include the `.` as part of the hyperlink, I believe this is html behavior so not much we can do there.

**Comment by TaroEld** [comment]
Likewise, I dont think there is an easy solution, or really any solution, apart from putting the dot in the link text.
