### ISSUE TITLE
Nested tooltip for Shieldwall does not work and produces errors while no shield is equipped

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/mod-reforged#499]
Problem is that the vanilla shieldwall (skill aswell as effect) require an item to generate their tooltip.
While the viewing brother has a shield equipped that barely works. Not so much without any item though.

![image](https://github.com/user-attachments/assets/bcabb930-4cba-46f4-805f-9403427f2dcf)

![image](https://github.com/user-attachments/assets/6471ea7e-ec61-494b-8996-0adbd6fbb646)

**Comment by LordMidas** [comment]
Is fixed as of Nested Tooltips Framework 0.1.6 which added a try/catch system to print the base tooltip when the actual tooltip throws errors.
